package org.omg.PortableServer;


/**
* org/omg/PortableServer/ID_ASSIGNMENT_POLICY_ID.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../src/share/classes/org/omg/PortableServer/poa.idl
* Tuesday, June 22, 2010 1:21:26 AM GMT-08:00
*/

public interface ID_ASSIGNMENT_POLICY_ID
{

  /**
	 * The value representing ID_ASSIGNMENT_POLICY_ID.
	 */
  public static final int value = (int)(19L);
}
