package org.omg.PortableInterceptor;


/**
* org/omg/PortableInterceptor/HOLDING.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../src/share/classes/org/omg/PortableInterceptor/Interceptors.idl
* Tuesday, June 22, 2010 1:21:30 AM GMT-08:00
*/

public interface HOLDING
{

  /** Object adapter state that holds requests temporarily until the 
   * state is changed.
   */
  public static final short value = (short)(0);
}
